version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-wordle
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongo-wordle
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: wordleuser
      MONGO_INITDB_ROOT_PASSWORD: wordlepass

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wordle-backend
    ports:
      - "8081:8080"
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_started
      mongo:
        condition: service_started
    env_file:
      - .env
